---
APP_NAME: muzix_recommender
APP_REPOSITORY: git@github.com:komuW/muzix_recommender.git
APP_USER: "{{ ansible_ssh_user }}"
APP_HOME: "/home/{{ APP_USER }}"
APP_DIR: "{{ APP_HOME }}/{{ APP_NAME }}"
APP_VIRTUALENV: "{{ APP_HOME }}/.virtualenvs/{{ APP_NAME }}"
APP_PORT: 80

RABBIT_MONIT_INTERVAL: 600 #in seconds
CELERY_WORKERS: 2
